apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dapi-test-pod-2
  name: dapi-test-pod-2
spec:
  containers:
  - image: busybox
    name: dapi-test-pod-2
    command: [ "/bin/sh", "-c", "env" ]  
    envFrom:
      - configMapRef:
          name: special-config  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
