apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dapi-test-pod-3
  name: dapi-test-pod-3
spec:
  containers:
  - image: busybox
    name: dapi-test-pod-3
    command: [ "/bin/sh", "-c", "env" ]  
    resources: {}
    command: ["sleep","1000"]  
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config  
  volumes:
  - name: config-volume
    configMap:
      name: special-config    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
